const {
    MessageEmbed
} = require("discord.js");
const request = require('request');
const cheerio = require('cheerio');
const config = require('../../config.json')
const token = config.token



/// SECTOR

var urls = [];
var values = [];
var changes = [];



module.exports = {
    name: "info",
    aliases: ['about', 'of'],
    description: "Shows the information of the share.",
    run: async (client, message, args) => {
        const sharename = args[0]
        request(`https://merolagani.com/CompanyDetail.aspx?symbol=`+`${sharename}`, function (err, resp, body) {
            if (!err && resp.statusCode == 200) {
                var $ = cheerio.load(body); // Sector
                $('tr .text-primary').each(function () {
                    var url = $(this).text();
                    urls.push(url);
                });
                var $ = cheerio.load(body); //Market Price
                $('#ctl00_ContentPlaceHolder1_CompanyDetail1_lblMarketPrice').each(function () {
                    var url = $(this).text();
                    values.push(url);
                });
                var $ = cheerio.load(body); //Change
                $('#ctl00_ContentPlaceHolder1_CompanyDetail1_lblChange').each(function () {
                    var url = $(this).text();
                    changes.push(url);
                });
                var $ = cheerio.load(body); //52 Weeks High Low 
                $('td').each(function () {
                    var url = $(this).text();
                    changes.push(url);
                });
            }

        });
        if (!sharename) {
            return message.channel.send('Enter the share ID you want information about.')
        }
        const msg = await message.channel.send('Genetating Latest Information....');
        const exampleEmbed = new MessageEmbed()
            .setColor('#87CEFA')
            .setURL(`https://merolagani.com/CompanyDetail.aspx?symbol=${sharename}`)
            .setTitle(`About ${sharename}`)
            .setThumbnail(message.author.displayAvatarURL())
            //    .setDescription('Here is the list of top losers.')
            .addFields({
                name: 'Sector',
                value: `${(urls[0])}`,
                inline: true
            }, {
                name: 'Market Price',
                value: `${(values[0])}`,
                inline: true
            }, {
                name: 'Change',
                value: `${(changes[0])}`,
                inline: true
            }, {
                name: '52 Weeks High - Low',
                value: `${(changes[6])}`,
                inline: true
            }, {
                name: '120 Day Average',
                value: `${(changes[8])}`,
                inline: true
            }, )
            ///     .setImage('https://cdn.discordapp.com/attachments/877137463078961173/877137498936053780/TOP_LOSERS.png')
            .setTimestamp()
            .setFooter('Generated By NEPSE Bot')
            msg.edit(exampleEmbed);
            
    }


}

