const {
    MessageEmbed
} = require("discord.js");
const prefix = require("../../config.json").prefix;
const request = require('request');
const cheerio = require('cheerio');

var urls = [];

request("https://merolagani.com/LatestMarket.aspx", function (err, resp, body) {
    if (!err && resp.statusCode == 200) {
        var $ = cheerio.load(body);
        $('.decrease a').each(function () {
            var url = $(this).text();
            urls.push(url);
        });

    }


});

module.exports = {
    name: "toplosers",
    aliases: ['tl', 'topl'],
    description: "Shows the list of todays top losers.",
    run: async (client, message, args) => {
        const exampleEmbed = new MessageEmbed()
            .setColor('#FF0000')
            .setTitle('Top Losers')
            .setDescription('Here is the list of top losers.')
            .addFields({
                name: '1st',
                value: `${(urls[0])}`,
                inline: true
            }, {
                name: '2nd',
                value: `${(urls[1])}`,
                inline: true
            }, {
                name: '3rd',
                value: `${(urls[2])}`,
                inline: true
            }, {
                name: '4th',
                value: `${(urls[3])}`,
                inline: true
            }, {
                name: '5th',
                value: `${(urls[4])}`,
                inline: true
            }, {
                name: '6th',
                value: `${(urls[5])}`,
                inline: true
            }, {
                name: '7th',
                value: `${(urls[6])}`,
                inline: true
            }, {
                name: '8th',
                value: `${(urls[7])}`,
                inline: true
            }, {
                name: '9th',
                value: `${(urls[8])}`,
                inline: true
            }, {
                name: '10th',
                value: `${(urls[9])}`,
                inline: true
            }, )
            .setImage('https://cdn.discordapp.com/attachments/877137463078961173/877137498936053780/TOP_LOSERS.png')
            .setTimestamp()
            .setFooter('Generated By NEPSE Bot')
        message.channel.send(exampleEmbed);

    }

}